services:
  broker-ui:
    build: .
    image: shadyelshrief/broker-karepo:latest
    container_name: broker-karepo-ui
    environment:
      FEEDER_HOST: host.docker.internal
      FEEDER_PORT: "7070"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8081:80"
